using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Datra.DataTypes;
using Datra.Providers;
using Datra.Repositories;
using Datra.Serializers;
using Xunit;

namespace Datra.Tests
{
    public class AssetRepositoryTests : IDisposable
    {
        private readonly string _testDirectory;
        private readonly FileSystemRawDataProvider _provider;
        private readonly DataSerializerFactory _serializerFactory;

        public AssetRepositoryTests()
        {
            _testDirectory = Path.Combine(Path.GetTempPath(), "DatraAssetTests_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_testDirectory);
            _provider = new FileSystemRawDataProvider(_testDirectory);
            _serializerFactory = new DataSerializerFactory();
        }

        public void Dispose()
        {
            if (Directory.Exists(_testDirectory))
            {
                Directory.Delete(_testDirectory, recursive: true);
            }
        }

        [Fact]
        public async Task LoadAsync_WithMetaFiles_LoadsAssetsWithCorrectIds()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets");
            Directory.CreateDirectory(dataFolder);

            // Create test files with .meta companions
            File.WriteAllText(Path.Combine(dataFolder, "script1.json"),
                "{\"Name\":\"Hello\",\"Value\":100}");
            File.WriteAllText(Path.Combine(dataFolder, "script1.json.datrameta"),
                "{\"Guid\":\"a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4\",\"DisplayName\":\"Hello Script\",\"Category\":\"Tutorial\"}");

            File.WriteAllText(Path.Combine(dataFolder, "script2.json"),
                "{\"Name\":\"World\",\"Value\":200}");
            File.WriteAllText(Path.Combine(dataFolder, "script2.json.datrameta"),
                "{\"Guid\":\"b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5\",\"DisplayName\":\"World Script\",\"Category\":\"Core\"}");

            var repository = new AssetRepository<TestAssetData>(
                "assets",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data),
                (obj, serializer) => serializer.SerializeSingle(obj)
            );

            // Act
            await repository.InitializeAsync();

            // Assert
            Assert.Equal(2, repository.Count);

            // Check that assets are loaded by GUID
            var guid1 = new AssetId(Guid.Parse("a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"));
            var guid2 = new AssetId(Guid.Parse("b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5"));

            Assert.True(repository.Contains(guid1));
            Assert.True(repository.Contains(guid2));

            var asset1 = await repository.GetAsync(guid1);
            Assert.Equal("Hello", asset1.Data.Name);
            Assert.Equal("Hello Script", asset1.Metadata.DisplayName);
            Assert.Equal("Tutorial", asset1.Metadata.Category);

            var asset2 = await repository.GetAsync(guid2);
            Assert.Equal("World", asset2.Data.Name);
        }

        [Fact]
        public async Task LoadAsync_WithoutMetaFiles_AutoGeneratesMeta()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_nometa");
            Directory.CreateDirectory(dataFolder);

            // Create test file WITHOUT .meta companion
            File.WriteAllText(Path.Combine(dataFolder, "auto.json"),
                "{\"Name\":\"AutoGenerated\",\"Value\":999}");

            var repository = new AssetRepository<TestAssetData>(
                "assets_nometa",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data),
                (obj, serializer) => serializer.SerializeSingle(obj)
            );

            // Act
            await repository.InitializeAsync();

            // Assert
            Assert.Equal(1, repository.Count);

            // Meta file should have been auto-generated
            Assert.True(File.Exists(Path.Combine(dataFolder, "auto.json.datrameta")));

            // Asset should have a valid GUID - load via Summary
            var summary = repository.Summaries.First();
            Assert.True(summary.Id.IsValid);

            var asset = await repository.GetAsync(summary.Id);
            Assert.NotNull(asset);
            Assert.Equal("AutoGenerated", asset!.Data.Name);
            Assert.Equal("auto", asset.Metadata.DisplayName); // Display name from filename
        }

        [Fact]
        public async Task GetByPath_ReturnsCorrectAsset()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_path");
            Directory.CreateDirectory(dataFolder);

            File.WriteAllText(Path.Combine(dataFolder, "test.json"),
                "{\"Name\":\"PathTest\",\"Value\":50}");
            File.WriteAllText(Path.Combine(dataFolder, "test.json.datrameta"),
                "{\"Guid\":\"c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6\"}");

            var repository = new AssetRepository<TestAssetData>(
                "assets_path",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            await repository.InitializeAsync();
            var asset = await repository.GetByPathAsync("test.json");

            // Assert
            Assert.NotNull(asset);
            Assert.Equal("PathTest", asset!.Data.Name);
        }

        [Fact]
        public async Task FindByCategory_ReturnsMatchingAssets()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_cat");
            Directory.CreateDirectory(dataFolder);

            File.WriteAllText(Path.Combine(dataFolder, "a.json"), "{\"Name\":\"A\",\"Value\":1}");
            File.WriteAllText(Path.Combine(dataFolder, "a.json.datrameta"),
                "{\"Guid\":\"11111111111111111111111111111111\",\"Category\":\"Combat\"}");

            File.WriteAllText(Path.Combine(dataFolder, "b.json"), "{\"Name\":\"B\",\"Value\":2}");
            File.WriteAllText(Path.Combine(dataFolder, "b.json.datrameta"),
                "{\"Guid\":\"22222222222222222222222222222222\",\"Category\":\"UI\"}");

            File.WriteAllText(Path.Combine(dataFolder, "c.json"), "{\"Name\":\"C\",\"Value\":3}");
            File.WriteAllText(Path.Combine(dataFolder, "c.json.datrameta"),
                "{\"Guid\":\"33333333333333333333333333333333\",\"Category\":\"Combat\"}");

            var repository = new AssetRepository<TestAssetData>(
                "assets_cat",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            await repository.InitializeAsync();
            var combatAssets = (await repository.FindAsync(s => s.Category == "Combat")).ToList();

            // Assert
            Assert.Equal(2, combatAssets.Count);
            Assert.Contains(combatAssets, a => a.Data.Name == "A");
            Assert.Contains(combatAssets, a => a.Data.Name == "C");
        }

        [Fact]
        public async Task FindByTag_ReturnsMatchingAssets()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_tag");
            Directory.CreateDirectory(dataFolder);

            File.WriteAllText(Path.Combine(dataFolder, "x.json"), "{\"Name\":\"X\",\"Value\":10}");
            File.WriteAllText(Path.Combine(dataFolder, "x.json.datrameta"),
                "{\"Guid\":\"44444444444444444444444444444444\",\"Tags\":[\"important\",\"featured\"]}");

            File.WriteAllText(Path.Combine(dataFolder, "y.json"), "{\"Name\":\"Y\",\"Value\":20}");
            File.WriteAllText(Path.Combine(dataFolder, "y.json.datrameta"),
                "{\"Guid\":\"55555555555555555555555555555555\",\"Tags\":[\"deprecated\"]}");

            var repository = new AssetRepository<TestAssetData>(
                "assets_tag",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            await repository.InitializeAsync();
            var importantAssets = (await repository.FindAsync(s => s.Tags != null && s.Tags.Contains("important"))).ToList();

            // Assert
            Assert.Single(importantAssets);
            Assert.Equal("X", importantAssets[0].Data.Name);
        }

        [Fact]
        public void Add_NewAsset_AddsWithNewGuid()
        {
            // Arrange
            var repository = new AssetRepository<TestAssetData>(
                "assets_add",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data),
                (obj, serializer) => serializer.SerializeSingle(obj)
            );

            var data = new TestAssetData { Name = "NewAsset", Value = 777 };

            // Act
            var asset = repository.Add(data, "new_asset.json");

            // Assert
            Assert.Equal(1, repository.Count);
            Assert.True(asset.Id.IsValid);
            Assert.Equal("NewAsset", asset.Data.Name);
            Assert.Equal("new_asset.json", asset.FilePath);
        }

        [Fact]
        public void Update_ExistingAsset_UpdatesData()
        {
            // Arrange
            var repository = new AssetRepository<TestAssetData>(
                "assets_update",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data),
                (obj, serializer) => serializer.SerializeSingle(obj)
            );

            var originalData = new TestAssetData { Name = "Original", Value = 100 };
            var asset = repository.Add(originalData, "update_test.json");
            var assetId = asset.Id;

            // Act
            var updatedData = new TestAssetData { Name = "Updated", Value = 200 };
            repository.Update(assetId, updatedData);

            // Assert - Use TryGetLoaded since Add already loads the asset
            var result = repository.TryGetLoaded(assetId);
            Assert.NotNull(result);
            Assert.Equal("Updated", result!.Data.Name);
            Assert.Equal(200, result.Data.Value);
        }

        [Fact]
        public void Remove_ExistingAsset_RemovesFromRepository()
        {
            // Arrange
            var repository = new AssetRepository<TestAssetData>(
                "assets_remove",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data),
                (obj, serializer) => serializer.SerializeSingle(obj)
            );

            var data = new TestAssetData { Name = "ToRemove", Value = 555 };
            var asset = repository.Add(data, "remove_test.json");
            var assetId = asset.Id;

            // Act
            var removed = repository.Remove(assetId);

            // Assert
            Assert.True(removed);
            Assert.Equal(0, repository.Count);
            Assert.False(repository.Contains(assetId));
        }

        [Fact]
        public async Task SaveAssetAsync_SavesDataAndMetaFiles()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_save");
            Directory.CreateDirectory(dataFolder);

            var repository = new AssetRepository<TestAssetData>(
                "assets_save",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data),
                (obj, serializer) => serializer.SerializeSingle(obj)
            );

            var data = new TestAssetData { Name = "SaveTest", Value = 888 };
            var asset = repository.Add(data, "saved_asset.json");

            // Act
            await repository.SaveAsync(asset.Id);

            // Assert
            var dataFilePath = Path.Combine(dataFolder, "saved_asset.json");
            var metaFilePath = Path.Combine(dataFolder, "saved_asset.json.datrameta");

            Assert.True(File.Exists(dataFilePath));
            Assert.True(File.Exists(metaFilePath));

            var savedContent = File.ReadAllText(dataFilePath);
            Assert.Contains("SaveTest", savedContent);
        }

        [Fact]
        public async Task LoadAsync_EmptyFolder_LoadsNoAssets()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "empty_assets");
            Directory.CreateDirectory(dataFolder);

            var repository = new AssetRepository<TestAssetData>(
                "empty_assets",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            await repository.InitializeAsync();

            // Assert
            Assert.Equal(0, repository.Count);
        }

        [Fact]
        public void TryGetById_NonExistent_ReturnsNull()
        {
            // Arrange
            var repository = new AssetRepository<TestAssetData>(
                "assets_try",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            var result = repository.TryGetLoaded(new AssetId(Guid.NewGuid()));

            // Assert
            Assert.Null(result);
        }

        [Fact]
        public async Task AssetRepository_ImplementsIReadOnlyDictionary()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_dict");
            Directory.CreateDirectory(dataFolder);

            File.WriteAllText(Path.Combine(dataFolder, "item1.json"),
                "{\"Name\":\"Item1\",\"Value\":100}");
            File.WriteAllText(Path.Combine(dataFolder, "item1.json.datrameta"),
                "{\"Guid\":\"11111111111111111111111111111111\"}");

            File.WriteAllText(Path.Combine(dataFolder, "item2.json"),
                "{\"Name\":\"Item2\",\"Value\":200}");
            File.WriteAllText(Path.Combine(dataFolder, "item2.json.datrameta"),
                "{\"Guid\":\"22222222222222222222222222222222\"}");

            var repository = new AssetRepository<TestAssetData>(
                "assets_dict",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            await repository.InitializeAsync();

            // Assert - Verify LoadedAssets dictionary
            var loadedAssets = repository.LoadedAssets;

            // Initially no assets are loaded (only summaries)
            // Let's load them first
            var guid1 = new AssetId(Guid.Parse("11111111111111111111111111111111"));
            var guid2 = new AssetId(Guid.Parse("22222222222222222222222222222222"));

            var asset1 = await repository.GetAsync(guid1);
            var asset2 = await repository.GetAsync(guid2);

            Assert.Equal(2, repository.LoadedAssets.Count);
            Assert.True(repository.LoadedAssets.ContainsKey(guid1));
            Assert.True(repository.LoadedAssets.TryGetValue(guid1, out var loadedAsset1));
            Assert.Equal("Item1", loadedAsset1!.Data.Name);

            // Enumeration
            var enumerated = repository.LoadedAssets.ToList();
            Assert.Equal(2, enumerated.Count);
        }

        [Fact]
        public async Task AssetRepository_CanBeUsedWithLinq()
        {
            // Arrange
            var dataFolder = Path.Combine(_testDirectory, "assets_linq");
            Directory.CreateDirectory(dataFolder);

            File.WriteAllText(Path.Combine(dataFolder, "high.json"),
                "{\"Name\":\"High\",\"Value\":500}");
            File.WriteAllText(Path.Combine(dataFolder, "high.json.datrameta"),
                "{\"Guid\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1\"}");

            File.WriteAllText(Path.Combine(dataFolder, "low.json"),
                "{\"Name\":\"Low\",\"Value\":50}");
            File.WriteAllText(Path.Combine(dataFolder, "low.json.datrameta"),
                "{\"Guid\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2\"}");

            var repository = new AssetRepository<TestAssetData>(
                "assets_linq",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act
            await repository.InitializeAsync();

            // Load all assets first
            var guid1 = new AssetId(Guid.Parse("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1"));
            var guid2 = new AssetId(Guid.Parse("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2"));
            await repository.GetAsync(guid1);
            await repository.GetAsync(guid2);

            // Assert - LINQ queries work on LoadedAssets
            var highValueAssets = repository.LoadedAssets
                .Where(kvp => kvp.Value.Data.Value > 100)
                .Select(kvp => kvp.Value)
                .ToList();

            Assert.Single(highValueAssets);
            Assert.Equal("High", highValueAssets[0].Data.Name);

            var allValues = repository.LoadedAssets.Values.Select(a => a.Data.Value).Sum();
            Assert.Equal(550, allValues);
        }

        [Fact]
        public void AssetRepository_EmptyRepository_ImplementsIReadOnlyDictionary()
        {
            // Arrange
            var repository = new AssetRepository<TestAssetData>(
                "empty_dict",
                "*.json",
                _provider,
                _serializerFactory,
                (data, serializer) => serializer.DeserializeSingle<TestAssetData>(data)
            );

            // Act & Assert - Empty repository should have empty LoadedAssets
            var loadedAssets = repository.LoadedAssets;

            Assert.Equal(0, loadedAssets.Count);
            Assert.Empty(loadedAssets.Keys);
            Assert.Empty(loadedAssets.Values);
            Assert.False(loadedAssets.ContainsKey(new AssetId(Guid.NewGuid())));
        }
    }

    // Test data class for asset tests (no ITableData - ID comes from metadata)
    public class TestAssetData
    {
        public string Name { get; set; } = string.Empty;
        public int Value { get; set; }
    }
}
